# Generated by Django 5.2.7 on 2025-11-06 02:27
from django.db import migrations

def crear_roles_iniciales(apps, schema_editor):
    # Obtenemos el modelo 'Rol' de la base de datos en este punto de la migración
    # Reemplaza 'prototipo' con el nombre de tu app si es diferente
    Rol = apps.get_model('Prototipo', 'Rol')
    
    # Lista de roles a crear: (nombre, descripción)
    roles = [
        ('Administrador', 'Control total sobre usuarios y configuración.'),
        ('Corredor', 'Crea, edita y elimina calificaciones.'),
        ('Auditor', 'Solo consulta registros y genera reportes.')
    ]

    for nombre, descripcion in roles:
        # Crea el objeto Rol
        Rol.objects.create(nombre=nombre, descripcion=descripcion)

class Migration(migrations.Migration):

    dependencies = [
        # Asegúrate de que esta dependencia apunte a la migración anterior 
        # (donde se creó la tabla Rol). Debería ser la última que tengas.
        ('Prototipo', '0001_initial'), 
    ]

    operations = [
        # Ejecuta la función crear_roles_iniciales
        migrations.RunPython(crear_roles_iniciales),
    ]