# Generated by Django 5.2.7 on 2025-11-07 00:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prototipo', '0002_auto_20251105_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={},
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='años',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='monto',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='archivo_carga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prototipo.archivocarga', verbose_name='Archivo de Carga Asociado'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='comentarios',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios Adicionales'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='emisor',
            field=models.CharField(max_length=255, verbose_name='Nombre del Emisor'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50, verbose_name='Estado de Calificación'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
    ]
