# Generated by Django 5.2.7 on 2025-11-07 04:59

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prototipo', '0003_alter_calificacion_options_remove_calificacion_años_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='emisor',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='años',
            field=models.IntegerField(default=1990),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='evento_capital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='fecha_pago',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='instrumento',
            field=models.CharField(default='SIN INSTRUMENTO', max_length=100),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='mercado',
            field=models.CharField(default='SIN MERCADO', max_length=50),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='origen',
            field=models.CharField(default='Manual', max_length=20),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='secuencia_evento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='valor_historico',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='archivo_carga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Prototipo.archivocarga'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='usuario_creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
